// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxaFSeoSaT6BZrHq93Z8E6vW9CKo-lLPg',
    appId: '1:153653758586:web:fbb218d44f80f90ff6c9c3',
    messagingSenderId: '153653758586',
    projectId: 'depi-r4',
    authDomain: 'depi-r4.firebaseapp.com',
    storageBucket: 'depi-r4.firebasestorage.app',
    measurementId: 'G-C3JVBVW1JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWnloaI-gSFyw9P1Mm8ReCg2D1-yyOn1c',
    appId: '1:153653758586:android:89304a380d74975cf6c9c3',
    messagingSenderId: '153653758586',
    projectId: 'depi-r4',
    storageBucket: 'depi-r4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkAD0NmGSPEBLgfBWSq8DVh1LjxiWN1gM',
    appId: '1:153653758586:ios:bab273801e48a35bf6c9c3',
    messagingSenderId: '153653758586',
    projectId: 'depi-r4',
    storageBucket: 'depi-r4.firebasestorage.app',
    iosBundleId: 'com.example.task1Flutter',
  );
}
